Decode stdout during documentation build (#628)
I think that I'm seeing this because doc builds are happening with
python 3 on Fedora. Here is the error I'm seeing:

```
...
  File "./rosdep_doc_utils.py", line 38, in run
    nodes.literal_block(text=re.sub(escaped_capitalized_usage, '', out))
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```